### ISSUE TITLE
Animation for mobile filters

### ISSUE THREAD

**Issue by yigitfindikli** [neu-fi/turkey-relief-dao#65]

**Comment by hantuzun** [comment]
Hi @yigitfindikli. I was going to open an issue for mobile filters. 

These are the missing feature parity:
* The default open tab
* Missing animations
* Missing organization count, in case some of them are filtered.

It'd be great if you could reuse a component so that such errors would be less likely in the future.

**Comment by hantuzun** [comment]
Another issue is the following scroll behavior: 

https://user-images.githubusercontent.com/2770895/218339961-40689b02-bbe4-412e-b1d4-91637e899c17.mov

Would you prefer me to open a new issue on that or would you prefer to update this issue and work on this too?

**Comment by yigitfindikli** [comment]
I think a new issue would be great.
