### ISSUE TITLE
Opening the filter panel causes a weird scroll behavior on mobile 

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#67]
Opening the filter panel has the following buggy scroll behavior:

https://user-images.githubusercontent.com/2770895/218340149-2fe50626-bee7-4cd2-8960-942c19c19630.mov

The issues below are fixed with https://github.com/neu-fi/turkiye-relief-dao/pull/68:

~~It's also missing feature parity with the desktop one:~~
 * ~~The first category is not expanded by default.~~
 * ~~When some organizations are filtered, the number indicator at the bottom is missing.~~
 
~~The last two issues better are resolved by reusing the code as a component. Contributors tend to omit to check the mobile view for them.~~

**Comment by hantuzun** [comment]
Added footage from a real phone:

https://user-images.githubusercontent.com/2770895/218346933-81f82910-819b-4634-b65e-0f27bd49b332.MOV

**Comment by hantuzun** [comment]
https://github.com/neu-fi/turkiye-relief-dao/pull/68 brought feature parity to the mobile filters; but did not fix the weird scroll behavior.

I observe the scroll behavior on iOS Safari and macOS Brave, but not on macOS Safari.

**Comment by hantuzun** [comment]
Is there anyone else that can replicate the issue?

**Comment by rogerfavelron** [comment]
> Is there anyone else that can replicate the issue?

https://app.usebubbles.com/93NuiPqrp4f2PVZCWK9RkC/osman-s-video-recording , I can replicate in MacOS Chrome

**Comment by oytuncoban** [comment]
It seems like the issue is caused by lacking of auto-focusable element in Dialog menu. Even the close button is focusable initially, I think browser cannot determine the button and automatically sets “filter” button as reference. However, I couldn't find why the scroll event is starting from (0,0). I've tried defining the refs manually, but it didn't work out. 

Solutions tried;

- Setting tabIndex to -1
- Using e.preventDefault()
- Using manual ref with React.useRef()

**Comment by rogerfavelron** [comment]
#90 , I believe this will fix our problem.
